name: CD

on:
  push:
    branches:
      - feature/deploy-to-ec2
      - main
      - develop
      - stg

jobs:
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull fabianflorez034/user-roles:latest
      - name: Delete old container
        run: sudo docker rm -f user-roles-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name user-roles-container fabianflorez034/user-roles